# Generated by Django 6.1.1 on 2026-10-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Research Essay'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField(help_text='Submission deadline datetime')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.unit')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'CAT 1'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cat_date', models.DateField(help_text='Date when the CAT takes place')),
                ('deadline', models.DateTimeField(blank=True, help_text='Specific deadline or start datetime if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='academics.unit')),
            ],
            options={
                'verbose_name': 'CAT',
                'verbose_name_plural': 'CATs',
                'ordering': ['cat_date', 'created_at'],
            },
        ),
    ]
