# Generated by Django 6.1.1 on 2026-10-03 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reminder_datetime', models.DateTimeField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='assessments.assignment')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='assessments.cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['reminder_datetime', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cat__isnull', False), ('assignment__isnull', True)), models.Q(('cat__isnull', True), ('assignment__isnull', False)), _connector='OR'), name='reminder_cat_or_assignment_required')],
            },
        ),
    ]
