# Generated by Django 5.2.17 on 2026-10-04 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='reminder_cat_or_assignment_required',
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('cat__isnull', False), ('assignment__isnull', False), _negated=True), name='reminder_not_both_cat_and_assignment'),
        ),
    ]
