# Generated by Django 5.2.17 on 2026-10-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_reminder_cat_or_assignment_required_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='reminder_not_both_cat_and_assignment',
        ),
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('CAT_REMINDER', 'CAT Reminder'), ('ASSIGNMENT_REMINDER', 'Assignment Reminder'), ('OTHER', 'Other Notification')], db_index=True, default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional note / description for this reminder'),
        ),
    ]
