# Generated by Django 5.2.17 on 2026-10-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Degree / Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, default='avatar1', max_length=500, verbose_name='Profile Photo / Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='School / University'),
        ),
    ]
