# Generated by Django 6.1.1 on 2026-10-03 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='unit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('semester', 'code')},
        ),
    ]
