# Generated by Django 5.2.17 on 2026-10-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lecturer_name',
            field=models.CharField(blank=True, default='', help_text="Lecturer's full name", max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='lecturer_phone',
            field=models.CharField(blank=True, default='', help_text="Lecturer's phone number (optional)", max_length=30),
        ),
    ]
